### ISSUE TITLE
Multiple observed properties

### ISSUE THREAD

**Issue by letmaik** [peterataylor/om-json#1]
Currently the schema supports a single observedProperty, which is a single link. Can you add an example how OM-JSON should be used when the result contains multiple observed properties, like temperature and wind speed?

**Comment by dr-shorthair** [comment]
Yes. This follows the O&M model - one observation generates one result, for one observed property.

If you want a compound result, then you have a compound observed property, but that must be packaged into one object or remote entity in order to conform to the model. There are a lot of examples, including in the O&M spec.

**Comment by letmaik** [comment]
The example in the spec measuring wind, temperature etc. has as observedProperty "http://sweet.jpl.nasa.gov/2.0/atmo.owl#Weather". But how useful is that as metadata? What if you want to create a search engine over O&M data files and provide some filter options like "give me every observation that measured temperature on 12/12/2005". Then having something generic as "Weather" is more or less useless and you would have to dig in to the result and understand that structure to extract the actual observed properties, which defeats the point of metadata. I know OM-JSON is not the place to discuss that, but I just wanted to raise the issue anyway. Feel free to close this issue though if there's no solution to this.

**Comment by dr-shorthair** [comment]
This is a real issue, but the solution is likely to be part of a broader consideration of compound types, probably related to work on models for tabular data (e.g. CSVW, RDA Data Types, OKFN data packages). Of real interest but we will not tackle it here and now.
